mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
unified-delay: true
ipv6: true
# global-client-fingerprint: chrome
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true # when the false, response to AAAA questions will be empty
  default-nameserver:
    - system
    - 114.114.114.114
  enhanced-mode: redir-host
  use-hosts: true # lookup hosts and return IP record
  nameserver:
    - https://dns.projectk.org/dns-query
    - https://1.1.1.1/dns-query#RULES
  nameserver-policy:
    "geosite:private":
      - system
    "rule-set:DnlabChina,GoogleCN,SteamCN,ChinaDomain":
      - https://tools.dnlab.net:16443/9c880947-bae6-4daa-beea-63f68a8df261/dns-query
      - https://dohcn.projectk.org/dns-query
    "geosite:cn":
      - https://tools.dnlab.net:16443/9c880947-bae6-4daa-beea-63f68a8df261/dns-query
      - https://dohcn.projectk.org/dns-query
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    QUIC:
      ports: [443]
    TLS:
      ports: [443, 16443]
    HTTP:
      ports: [80, 8080, 16080]
  skip-domain:
    - Mijia Cloud
