mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
ipv6: true
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true # when the false, response to AAAA questions will be empty
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
  # enhanced-mode: fake-ip
  # fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: true # lookup hosts and return IP record
  nameserver:
    # - https://api.dnlab.net/9FE8749B-0E86-582D-E33F-08204D58F81B
    - https://1.1.1.1/dns-query # DNS over HTTPS
    # - https://1.0.0.1/dns-query # DNS over HTTPS
    # - https://8.8.8.8/dns-query # DNS over HTTPS
    # - https://8.8.4.4/dns-query # DNS over HTTPS
  fallback:
    - https://1.1.1.1/dns-query # DNS over HTTPS
    - https://1.0.0.1/dns-query # DNS over HTTPS
    - https://8.8.8.8/dns-query # DNS over HTTPS
    - https://8.8.4.4/dns-query # DNS over HTTPS
  fallback-filter:
    geoip: false
    # geoip-code: CN
    # ipcidr:
    #   - 0.0.0.0/0
    #   - ::/0
    domain:
      - "*"
