mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
ipv6: true
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true # when the false, response to AAAA questions will be empty
  default-nameserver:
    - 1.1.1.1
    # - 1.0.0.1
    - 8.8.8.8
    # - 8.8.4.4
    - "[2602:f9df:111::1111]:53"
    - 114.114.114.114
  # enhanced-mode: fake-ip
  # fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: true # lookup hosts and return IP record
  nameserver:
    - https://dns.kawaii.net.cn/dns-query
    - https://api.dnlab.net:16443/9FE8749B-0E86-582D-E33F-08204D58F81B/dns-query
    # - https://dns.tuna.tsinghua.edu.cn:8443/dns-query
    # - https://1.1.1.1/dns-query # DNS over HTTPS
    # - https://1.0.0.1/dns-query # DNS over HTTPS
    # - https://8.8.8.8/dns-query # DNS over HTTPS
    # - https://8.8.4.4/dns-query # DNS over HTTPS
  fallback: # fallback dns use proxy according to https://github.com/Dreamacro/clash/issues/681
    - https://1.1.1.1/dns-query # DNS over HTTPS
    - https://1.0.0.1/dns-query # DNS over HTTPS
    - https://8.8.8.8/dns-query # DNS over HTTPS
    - https://8.8.4.4/dns-query # DNS over HTTPS
    - https://dns.kawaii.net.cn/dns-query
    - https://api.dnlab.net:16443/9FE8749B-0E86-582D-E33F-08204D58F81B/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    # ipcidr:
    #   - 0.0.0.0/0
    #   - ::/0
    # domain:
    #   - "*.*" # All domain will use fallback, this filter may be wrong. check https://github.com/Dreamacro/clash/blob/master/component/trie/domain.go for more information
